import Head from "next/head";
import React, { useState, useEffect } from "react";
import axios from "axios";
import { Button, Form, Input, Select, Spin, message } from "antd";
import { useRouter } from "next/router";

const { Option } = Select;

export default function Categoria() {
  const router = useRouter();
  const { id } = router.query;
  const [form] = Form.useForm();
  const [category, setCategory] = useState(null);
  const [loading, setLoading] = useState(!!id);

  useEffect(() => {
    if (id) {
      axios
        .get(`/api/categories/${id}`)
        .then((response) => {
          setCategory(response.data);
          setLoading(false);
        })
        .catch(() => {
          message.error("Erro ao carregar a categoria.");
          setLoading(false);
        });
    }
  }, [id]);

  const onFinish = async (values) => {
    try {
      if (category) {
        await axios.put(`/api/categories/${category.id}`, values);
        message.success("Categoria atualizada com sucesso!");
      } else {
        await axios.post("/api/categories", values);
        message.success("Categoria criada com sucesso!");
      }
      handleSuccess();
    } catch (error) {
      message.error("Erro ao salvar a categoria.");
    }
  };

  const handleSuccess = () => {
    router.push("/categories");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {loading ? (
          <Spin size="large" />
        ) : (
          <Form
            form={form}
            initialValues={category}
            onFinish={onFinish}
            layout="vertical"
          >
            <Form.Item
              name="name"
              label="Nome da Categoria"
              rules={[
                {
                  required: true,
                  message: "Por favor, insira o nome da categoria!",
                },
              ]}
            >
              <Input />
            </Form.Item>

            <Form.Item
              name="type"
              label="Tipo"
              rules={[
                { required: true, message: "Por favor, selecione o tipo!" },
              ]}
            >
              <Select placeholder="Selecione um tipo">
                <Option value="income">Receita</Option>
                <Option value="expense">Despesa</Option>
              </Select>
            </Form.Item>

            <Form.Item>
              <Button type="primary" htmlType="submit">
                Salvar
              </Button>
            </Form.Item>
          </Form>
        )}
      </main>
    </>
  );
}
