import { Inter } from "next/font/google";
import styles from "@/styles/layout.module.css";
import ptBR from "antd/lib/locale/pt_BR";
import { ConfigProvider } from "antd";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider locale={ptBR}>
          <section className={styles?.layout}>{children}</section>
        </ConfigProvider>
      </body>
    </html>
  );
}
